image: ruby:2.3

test:
  stage: test
  script:
  - gem install jekyll
  - gem install redcarpet
  - gem install jekyll-paginate
  - gem install jekyll-gist
  - gem install jekyll-sitemap
  - gem install jekyll-seo-tag
  - gem install jekyll-archives
  - jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll
  - gem install redcarpet
  - gem install jekyll-paginate
  - gem install jekyll-gist
  - gem install jekyll-sitemap
  - gem install jekyll-seo-tag
  - gem install jekyll-archives
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
